// Code generated by HashPost Generated Code. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/matt0x6f/hashpost/internal/database/models"
	"github.com/stephenafamo/bob"
)

type KeyRotationMigrationMod interface {
	Apply(context.Context, *KeyRotationMigrationTemplate)
}

type KeyRotationMigrationModFunc func(context.Context, *KeyRotationMigrationTemplate)

func (f KeyRotationMigrationModFunc) Apply(ctx context.Context, n *KeyRotationMigrationTemplate) {
	f(ctx, n)
}

type KeyRotationMigrationModSlice []KeyRotationMigrationMod

func (mods KeyRotationMigrationModSlice) Apply(ctx context.Context, n *KeyRotationMigrationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// KeyRotationMigrationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type KeyRotationMigrationTemplate struct {
	MigrationID      func() uuid.UUID
	Domain           func() string
	OldKeyVersion    func() int32
	NewKeyVersion    func() int32
	Status           func() string
	StartedAt        func() sql.Null[time.Time]
	PausedAt         func() sql.Null[time.Time]
	ResumedAt        func() sql.Null[time.Time]
	CompletedAt      func() sql.Null[time.Time]
	TotalRecords     func() sql.Null[int64]
	ProcessedRecords func() sql.Null[int64]
	FailedRecords    func() sql.Null[int64]
	LastProcessedID  func() sql.Null[uuid.UUID]
	ErrorMessage     func() sql.Null[string]
	RetryCount       func() sql.Null[int32]
	MaxRetries       func() sql.Null[int32]
	CreatedBy        func() int64

	r keyRotationMigrationR
	f *Factory
}

type keyRotationMigrationR struct {
	CreatedByUser                *keyRotationMigrationRCreatedByUserR
	MigrationMigrationProgresses []*keyRotationMigrationRMigrationMigrationProgressesR
}

type keyRotationMigrationRCreatedByUserR struct {
	o *UserTemplate
}
type keyRotationMigrationRMigrationMigrationProgressesR struct {
	number int
	o      *MigrationProgressTemplate
}

// Apply mods to the KeyRotationMigrationTemplate
func (o *KeyRotationMigrationTemplate) Apply(ctx context.Context, mods ...KeyRotationMigrationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.KeyRotationMigration
// according to the relationships in the template. Nothing is inserted into the db
func (t KeyRotationMigrationTemplate) setModelRels(o *models.KeyRotationMigration) {
	if t.r.CreatedByUser != nil {
		rel := t.r.CreatedByUser.o.Build()
		rel.R.CreatedByKeyRotationMigrations = append(rel.R.CreatedByKeyRotationMigrations, o)
		o.CreatedBy = rel.UserID // h2
		o.R.CreatedByUser = rel
	}

	if t.r.MigrationMigrationProgresses != nil {
		rel := models.MigrationProgressSlice{}
		for _, r := range t.r.MigrationMigrationProgresses {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.MigrationID = o.MigrationID // h2
				rel.R.MigrationKeyRotationMigration = o
			}
			rel = append(rel, related...)
		}
		o.R.MigrationMigrationProgresses = rel
	}
}

// BuildSetter returns an *models.KeyRotationMigrationSetter
// this does nothing with the relationship templates
func (o KeyRotationMigrationTemplate) BuildSetter() *models.KeyRotationMigrationSetter {
	m := &models.KeyRotationMigrationSetter{}

	if o.MigrationID != nil {
		val := o.MigrationID()
		m.MigrationID = &val
	}
	if o.Domain != nil {
		val := o.Domain()
		m.Domain = &val
	}
	if o.OldKeyVersion != nil {
		val := o.OldKeyVersion()
		m.OldKeyVersion = &val
	}
	if o.NewKeyVersion != nil {
		val := o.NewKeyVersion()
		m.NewKeyVersion = &val
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = &val
	}
	if o.StartedAt != nil {
		val := o.StartedAt()
		m.StartedAt = &val
	}
	if o.PausedAt != nil {
		val := o.PausedAt()
		m.PausedAt = &val
	}
	if o.ResumedAt != nil {
		val := o.ResumedAt()
		m.ResumedAt = &val
	}
	if o.CompletedAt != nil {
		val := o.CompletedAt()
		m.CompletedAt = &val
	}
	if o.TotalRecords != nil {
		val := o.TotalRecords()
		m.TotalRecords = &val
	}
	if o.ProcessedRecords != nil {
		val := o.ProcessedRecords()
		m.ProcessedRecords = &val
	}
	if o.FailedRecords != nil {
		val := o.FailedRecords()
		m.FailedRecords = &val
	}
	if o.LastProcessedID != nil {
		val := o.LastProcessedID()
		m.LastProcessedID = &val
	}
	if o.ErrorMessage != nil {
		val := o.ErrorMessage()
		m.ErrorMessage = &val
	}
	if o.RetryCount != nil {
		val := o.RetryCount()
		m.RetryCount = &val
	}
	if o.MaxRetries != nil {
		val := o.MaxRetries()
		m.MaxRetries = &val
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = &val
	}

	return m
}

// BuildManySetter returns an []*models.KeyRotationMigrationSetter
// this does nothing with the relationship templates
func (o KeyRotationMigrationTemplate) BuildManySetter(number int) []*models.KeyRotationMigrationSetter {
	m := make([]*models.KeyRotationMigrationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.KeyRotationMigration
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KeyRotationMigrationTemplate.Create
func (o KeyRotationMigrationTemplate) Build() *models.KeyRotationMigration {
	m := &models.KeyRotationMigration{}

	if o.MigrationID != nil {
		m.MigrationID = o.MigrationID()
	}
	if o.Domain != nil {
		m.Domain = o.Domain()
	}
	if o.OldKeyVersion != nil {
		m.OldKeyVersion = o.OldKeyVersion()
	}
	if o.NewKeyVersion != nil {
		m.NewKeyVersion = o.NewKeyVersion()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.StartedAt != nil {
		m.StartedAt = o.StartedAt()
	}
	if o.PausedAt != nil {
		m.PausedAt = o.PausedAt()
	}
	if o.ResumedAt != nil {
		m.ResumedAt = o.ResumedAt()
	}
	if o.CompletedAt != nil {
		m.CompletedAt = o.CompletedAt()
	}
	if o.TotalRecords != nil {
		m.TotalRecords = o.TotalRecords()
	}
	if o.ProcessedRecords != nil {
		m.ProcessedRecords = o.ProcessedRecords()
	}
	if o.FailedRecords != nil {
		m.FailedRecords = o.FailedRecords()
	}
	if o.LastProcessedID != nil {
		m.LastProcessedID = o.LastProcessedID()
	}
	if o.ErrorMessage != nil {
		m.ErrorMessage = o.ErrorMessage()
	}
	if o.RetryCount != nil {
		m.RetryCount = o.RetryCount()
	}
	if o.MaxRetries != nil {
		m.MaxRetries = o.MaxRetries()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.KeyRotationMigrationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KeyRotationMigrationTemplate.CreateMany
func (o KeyRotationMigrationTemplate) BuildMany(number int) models.KeyRotationMigrationSlice {
	m := make(models.KeyRotationMigrationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableKeyRotationMigration(m *models.KeyRotationMigrationSetter) {
	if m.Domain == nil {
		val := random_string(nil, "100")
		m.Domain = &val
	}
	if m.OldKeyVersion == nil {
		val := random_int32(nil)
		m.OldKeyVersion = &val
	}
	if m.NewKeyVersion == nil {
		val := random_int32(nil)
		m.NewKeyVersion = &val
	}
	if m.CreatedBy == nil {
		val := random_int64(nil)
		m.CreatedBy = &val
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.KeyRotationMigration
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *KeyRotationMigrationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.KeyRotationMigration) (context.Context, error) {
	var err error

	isMigrationMigrationProgressesDone, _ := keyRotationMigrationRelMigrationMigrationProgressesCtx.Value(ctx)
	if !isMigrationMigrationProgressesDone && o.r.MigrationMigrationProgresses != nil {
		ctx = keyRotationMigrationRelMigrationMigrationProgressesCtx.WithValue(ctx, true)
		for _, r := range o.r.MigrationMigrationProgresses {
			var rel1 models.MigrationProgressSlice
			ctx, rel1, err = r.o.createMany(ctx, exec, r.number)
			if err != nil {
				return ctx, err
			}

			err = m.AttachMigrationMigrationProgresses(ctx, exec, rel1...)
			if err != nil {
				return ctx, err
			}
		}
	}

	return ctx, err
}

// Create builds a keyRotationMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *KeyRotationMigrationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.KeyRotationMigration, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a keyRotationMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *KeyRotationMigrationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.KeyRotationMigration {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a keyRotationMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *KeyRotationMigrationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.KeyRotationMigration {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a keyRotationMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *KeyRotationMigrationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.KeyRotationMigration, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableKeyRotationMigration(opt)

	if o.r.CreatedByUser == nil {
		KeyRotationMigrationMods.WithNewCreatedByUser().Apply(ctx, o)
	}

	rel0, ok := userCtx.Value(ctx)
	if !ok {
		ctx, rel0, err = o.r.CreatedByUser.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	opt.CreatedBy = &rel0.UserID

	m, err := models.KeyRotationMigrations.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = keyRotationMigrationCtx.WithValue(ctx, m)

	m.R.CreatedByUser = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple keyRotationMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o KeyRotationMigrationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.KeyRotationMigrationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple keyRotationMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o KeyRotationMigrationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.KeyRotationMigrationSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple keyRotationMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o KeyRotationMigrationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.KeyRotationMigrationSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple keyRotationMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o KeyRotationMigrationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.KeyRotationMigrationSlice, error) {
	var err error
	m := make(models.KeyRotationMigrationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// KeyRotationMigration has methods that act as mods for the KeyRotationMigrationTemplate
var KeyRotationMigrationMods keyRotationMigrationMods

type keyRotationMigrationMods struct{}

func (m keyRotationMigrationMods) RandomizeAllColumns(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModSlice{
		KeyRotationMigrationMods.RandomMigrationID(f),
		KeyRotationMigrationMods.RandomDomain(f),
		KeyRotationMigrationMods.RandomOldKeyVersion(f),
		KeyRotationMigrationMods.RandomNewKeyVersion(f),
		KeyRotationMigrationMods.RandomStatus(f),
		KeyRotationMigrationMods.RandomStartedAt(f),
		KeyRotationMigrationMods.RandomPausedAt(f),
		KeyRotationMigrationMods.RandomResumedAt(f),
		KeyRotationMigrationMods.RandomCompletedAt(f),
		KeyRotationMigrationMods.RandomTotalRecords(f),
		KeyRotationMigrationMods.RandomProcessedRecords(f),
		KeyRotationMigrationMods.RandomFailedRecords(f),
		KeyRotationMigrationMods.RandomLastProcessedID(f),
		KeyRotationMigrationMods.RandomErrorMessage(f),
		KeyRotationMigrationMods.RandomRetryCount(f),
		KeyRotationMigrationMods.RandomMaxRetries(f),
		KeyRotationMigrationMods.RandomCreatedBy(f),
	}
}

// Set the model columns to this value
func (m keyRotationMigrationMods) MigrationID(val uuid.UUID) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MigrationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) MigrationIDFunc(f func() uuid.UUID) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MigrationID = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetMigrationID() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MigrationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomMigrationID(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MigrationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) Domain(val string) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Domain = func() string { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) DomainFunc(f func() string) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Domain = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetDomain() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Domain = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomDomain(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Domain = func() string {
			return random_string(f, "100")
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) OldKeyVersion(val int32) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.OldKeyVersion = func() int32 { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) OldKeyVersionFunc(f func() int32) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.OldKeyVersion = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetOldKeyVersion() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.OldKeyVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomOldKeyVersion(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.OldKeyVersion = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) NewKeyVersion(val int32) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.NewKeyVersion = func() int32 { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) NewKeyVersionFunc(f func() int32) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.NewKeyVersion = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetNewKeyVersion() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.NewKeyVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomNewKeyVersion(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.NewKeyVersion = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) Status(val string) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) StatusFunc(f func() string) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetStatus() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomStatus(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.Status = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) StartedAt(val sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.StartedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) StartedAtFunc(f func() sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.StartedAt = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetStartedAt() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.StartedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomStartedAt(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.StartedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomStartedAtNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.StartedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) PausedAt(val sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.PausedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) PausedAtFunc(f func() sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.PausedAt = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetPausedAt() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.PausedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomPausedAt(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.PausedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomPausedAtNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.PausedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) ResumedAt(val sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ResumedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) ResumedAtFunc(f func() sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ResumedAt = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetResumedAt() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ResumedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomResumedAt(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ResumedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomResumedAtNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ResumedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) CompletedAt(val sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) CompletedAtFunc(f func() sql.Null[time.Time]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CompletedAt = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetCompletedAt() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CompletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomCompletedAt(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomCompletedAtNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) TotalRecords(val sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.TotalRecords = func() sql.Null[int64] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) TotalRecordsFunc(f func() sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.TotalRecords = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetTotalRecords() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.TotalRecords = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomTotalRecords(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.TotalRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomTotalRecordsNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.TotalRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) ProcessedRecords(val sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ProcessedRecords = func() sql.Null[int64] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) ProcessedRecordsFunc(f func() sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ProcessedRecords = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetProcessedRecords() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ProcessedRecords = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomProcessedRecords(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ProcessedRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomProcessedRecordsNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ProcessedRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) FailedRecords(val sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.FailedRecords = func() sql.Null[int64] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) FailedRecordsFunc(f func() sql.Null[int64]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.FailedRecords = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetFailedRecords() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.FailedRecords = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomFailedRecords(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.FailedRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomFailedRecordsNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.FailedRecords = func() sql.Null[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return sql.Null[int64]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) LastProcessedID(val sql.Null[uuid.UUID]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.LastProcessedID = func() sql.Null[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) LastProcessedIDFunc(f func() sql.Null[uuid.UUID]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.LastProcessedID = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetLastProcessedID() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.LastProcessedID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomLastProcessedID(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.LastProcessedID = func() sql.Null[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return sql.Null[uuid.UUID]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomLastProcessedIDNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.LastProcessedID = func() sql.Null[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return sql.Null[uuid.UUID]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) ErrorMessage(val sql.Null[string]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ErrorMessage = func() sql.Null[string] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) ErrorMessageFunc(f func() sql.Null[string]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ErrorMessage = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetErrorMessage() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ErrorMessage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomErrorMessage(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ErrorMessage = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomErrorMessageNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.ErrorMessage = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) RetryCount(val sql.Null[int32]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.RetryCount = func() sql.Null[int32] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) RetryCountFunc(f func() sql.Null[int32]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.RetryCount = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetRetryCount() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.RetryCount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomRetryCount(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.RetryCount = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomRetryCountNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.RetryCount = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) MaxRetries(val sql.Null[int32]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MaxRetries = func() sql.Null[int32] { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) MaxRetriesFunc(f func() sql.Null[int32]) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MaxRetries = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetMaxRetries() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MaxRetries = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m keyRotationMigrationMods) RandomMaxRetries(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MaxRetries = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m keyRotationMigrationMods) RandomMaxRetriesNotNull(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.MaxRetries = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m keyRotationMigrationMods) CreatedBy(val int64) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CreatedBy = func() int64 { return val }
	})
}

// Set the Column from the function
func (m keyRotationMigrationMods) CreatedByFunc(f func() int64) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m keyRotationMigrationMods) UnsetCreatedBy() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keyRotationMigrationMods) RandomCreatedBy(f *faker.Faker) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(_ context.Context, o *KeyRotationMigrationTemplate) {
		o.CreatedBy = func() int64 {
			return random_int64(f)
		}
	})
}

func (m keyRotationMigrationMods) WithParentsCascading() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		if isDone, _ := keyRotationMigrationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = keyRotationMigrationWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUser(ctx, UserMods.WithParentsCascading())
			m.WithCreatedByUser(related).Apply(ctx, o)
		}
	})
}

func (m keyRotationMigrationMods) WithCreatedByUser(rel *UserTemplate) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		o.r.CreatedByUser = &keyRotationMigrationRCreatedByUserR{
			o: rel,
		}
	})
}

func (m keyRotationMigrationMods) WithNewCreatedByUser(mods ...UserMod) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		related := o.f.NewUser(ctx, mods...)

		m.WithCreatedByUser(related).Apply(ctx, o)
	})
}

func (m keyRotationMigrationMods) WithoutCreatedByUser() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		o.r.CreatedByUser = nil
	})
}

func (m keyRotationMigrationMods) WithMigrationMigrationProgresses(number int, related *MigrationProgressTemplate) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		o.r.MigrationMigrationProgresses = []*keyRotationMigrationRMigrationMigrationProgressesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m keyRotationMigrationMods) WithNewMigrationMigrationProgresses(number int, mods ...MigrationProgressMod) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		related := o.f.NewMigrationProgress(ctx, mods...)
		m.WithMigrationMigrationProgresses(number, related).Apply(ctx, o)
	})
}

func (m keyRotationMigrationMods) AddMigrationMigrationProgresses(number int, related *MigrationProgressTemplate) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		o.r.MigrationMigrationProgresses = append(o.r.MigrationMigrationProgresses, &keyRotationMigrationRMigrationMigrationProgressesR{
			number: number,
			o:      related,
		})
	})
}

func (m keyRotationMigrationMods) AddNewMigrationMigrationProgresses(number int, mods ...MigrationProgressMod) KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		related := o.f.NewMigrationProgress(ctx, mods...)
		m.AddMigrationMigrationProgresses(number, related).Apply(ctx, o)
	})
}

func (m keyRotationMigrationMods) WithoutMigrationMigrationProgresses() KeyRotationMigrationMod {
	return KeyRotationMigrationModFunc(func(ctx context.Context, o *KeyRotationMigrationTemplate) {
		o.r.MigrationMigrationProgresses = nil
	})
}
