// Code generated by HashPost Generated Code. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/matt0x6f/hashpost/internal/database/models"
	"github.com/stephenafamo/bob"
)

type MigrationProgressMod interface {
	Apply(context.Context, *MigrationProgressTemplate)
}

type MigrationProgressModFunc func(context.Context, *MigrationProgressTemplate)

func (f MigrationProgressModFunc) Apply(ctx context.Context, n *MigrationProgressTemplate) {
	f(ctx, n)
}

type MigrationProgressModSlice []MigrationProgressMod

func (mods MigrationProgressModSlice) Apply(ctx context.Context, n *MigrationProgressTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MigrationProgressTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MigrationProgressTemplate struct {
	MigrationID  func() uuid.UUID
	MappingID    func() uuid.UUID
	Status       func() string
	StartedAt    func() sql.Null[time.Time]
	CompletedAt  func() sql.Null[time.Time]
	ErrorMessage func() sql.Null[string]
	RetryCount   func() sql.Null[int32]
	MaxRetries   func() sql.Null[int32]

	r migrationProgressR
	f *Factory
}

type migrationProgressR struct {
	MappingIdentityMapping        *migrationProgressRMappingIdentityMappingR
	MigrationKeyRotationMigration *migrationProgressRMigrationKeyRotationMigrationR
}

type migrationProgressRMappingIdentityMappingR struct {
	o *IdentityMappingTemplate
}
type migrationProgressRMigrationKeyRotationMigrationR struct {
	o *KeyRotationMigrationTemplate
}

// Apply mods to the MigrationProgressTemplate
func (o *MigrationProgressTemplate) Apply(ctx context.Context, mods ...MigrationProgressMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MigrationProgress
// according to the relationships in the template. Nothing is inserted into the db
func (t MigrationProgressTemplate) setModelRels(o *models.MigrationProgress) {
	if t.r.MappingIdentityMapping != nil {
		rel := t.r.MappingIdentityMapping.o.Build()
		rel.R.MappingMigrationProgresses = append(rel.R.MappingMigrationProgresses, o)
		o.MappingID = rel.MappingID // h2
		o.R.MappingIdentityMapping = rel
	}

	if t.r.MigrationKeyRotationMigration != nil {
		rel := t.r.MigrationKeyRotationMigration.o.Build()
		rel.R.MigrationMigrationProgresses = append(rel.R.MigrationMigrationProgresses, o)
		o.MigrationID = rel.MigrationID // h2
		o.R.MigrationKeyRotationMigration = rel
	}
}

// BuildSetter returns an *models.MigrationProgressSetter
// this does nothing with the relationship templates
func (o MigrationProgressTemplate) BuildSetter() *models.MigrationProgressSetter {
	m := &models.MigrationProgressSetter{}

	if o.MigrationID != nil {
		val := o.MigrationID()
		m.MigrationID = &val
	}
	if o.MappingID != nil {
		val := o.MappingID()
		m.MappingID = &val
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = &val
	}
	if o.StartedAt != nil {
		val := o.StartedAt()
		m.StartedAt = &val
	}
	if o.CompletedAt != nil {
		val := o.CompletedAt()
		m.CompletedAt = &val
	}
	if o.ErrorMessage != nil {
		val := o.ErrorMessage()
		m.ErrorMessage = &val
	}
	if o.RetryCount != nil {
		val := o.RetryCount()
		m.RetryCount = &val
	}
	if o.MaxRetries != nil {
		val := o.MaxRetries()
		m.MaxRetries = &val
	}

	return m
}

// BuildManySetter returns an []*models.MigrationProgressSetter
// this does nothing with the relationship templates
func (o MigrationProgressTemplate) BuildManySetter(number int) []*models.MigrationProgressSetter {
	m := make([]*models.MigrationProgressSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MigrationProgress
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationProgressTemplate.Create
func (o MigrationProgressTemplate) Build() *models.MigrationProgress {
	m := &models.MigrationProgress{}

	if o.MigrationID != nil {
		m.MigrationID = o.MigrationID()
	}
	if o.MappingID != nil {
		m.MappingID = o.MappingID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.StartedAt != nil {
		m.StartedAt = o.StartedAt()
	}
	if o.CompletedAt != nil {
		m.CompletedAt = o.CompletedAt()
	}
	if o.ErrorMessage != nil {
		m.ErrorMessage = o.ErrorMessage()
	}
	if o.RetryCount != nil {
		m.RetryCount = o.RetryCount()
	}
	if o.MaxRetries != nil {
		m.MaxRetries = o.MaxRetries()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MigrationProgressSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationProgressTemplate.CreateMany
func (o MigrationProgressTemplate) BuildMany(number int) models.MigrationProgressSlice {
	m := make(models.MigrationProgressSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMigrationProgress(m *models.MigrationProgressSetter) {
	if m.MigrationID == nil {
		val := random_uuid_UUID(nil)
		m.MigrationID = &val
	}
	if m.MappingID == nil {
		val := random_uuid_UUID(nil)
		m.MappingID = &val
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MigrationProgress
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MigrationProgressTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MigrationProgress) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a migrationProgress and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MigrationProgressTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MigrationProgress, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a migrationProgress and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MigrationProgressTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MigrationProgress {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a migrationProgress and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MigrationProgressTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MigrationProgress {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a migrationProgress and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *MigrationProgressTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.MigrationProgress, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMigrationProgress(opt)

	if o.r.MappingIdentityMapping == nil {
		MigrationProgressMods.WithNewMappingIdentityMapping().Apply(ctx, o)
	}

	rel0, ok := identityMappingCtx.Value(ctx)
	if !ok {
		ctx, rel0, err = o.r.MappingIdentityMapping.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	opt.MappingID = &rel0.MappingID

	if o.r.MigrationKeyRotationMigration == nil {
		MigrationProgressMods.WithNewMigrationKeyRotationMigration().Apply(ctx, o)
	}

	rel1, ok := keyRotationMigrationCtx.Value(ctx)
	if !ok {
		ctx, rel1, err = o.r.MigrationKeyRotationMigration.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	opt.MigrationID = &rel1.MigrationID

	m, err := models.MigrationProgresses.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = migrationProgressCtx.WithValue(ctx, m)

	m.R.MappingIdentityMapping = rel0
	m.R.MigrationKeyRotationMigration = rel1

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple migrationProgresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MigrationProgressTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MigrationProgressSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple migrationProgresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MigrationProgressTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MigrationProgressSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple migrationProgresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MigrationProgressTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MigrationProgressSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple migrationProgresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o MigrationProgressTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.MigrationProgressSlice, error) {
	var err error
	m := make(models.MigrationProgressSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// MigrationProgress has methods that act as mods for the MigrationProgressTemplate
var MigrationProgressMods migrationProgressMods

type migrationProgressMods struct{}

func (m migrationProgressMods) RandomizeAllColumns(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModSlice{
		MigrationProgressMods.RandomMigrationID(f),
		MigrationProgressMods.RandomMappingID(f),
		MigrationProgressMods.RandomStatus(f),
		MigrationProgressMods.RandomStartedAt(f),
		MigrationProgressMods.RandomCompletedAt(f),
		MigrationProgressMods.RandomErrorMessage(f),
		MigrationProgressMods.RandomRetryCount(f),
		MigrationProgressMods.RandomMaxRetries(f),
	}
}

// Set the model columns to this value
func (m migrationProgressMods) MigrationID(val uuid.UUID) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MigrationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) MigrationIDFunc(f func() uuid.UUID) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MigrationID = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetMigrationID() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MigrationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationProgressMods) RandomMigrationID(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MigrationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) MappingID(val uuid.UUID) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MappingID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) MappingIDFunc(f func() uuid.UUID) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MappingID = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetMappingID() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MappingID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationProgressMods) RandomMappingID(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MappingID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) Status(val string) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) StatusFunc(f func() string) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetStatus() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationProgressMods) RandomStatus(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.Status = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) StartedAt(val sql.Null[time.Time]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.StartedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) StartedAtFunc(f func() sql.Null[time.Time]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.StartedAt = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetStartedAt() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.StartedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m migrationProgressMods) RandomStartedAt(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.StartedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m migrationProgressMods) RandomStartedAtNotNull(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.StartedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) CompletedAt(val sql.Null[time.Time]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) CompletedAtFunc(f func() sql.Null[time.Time]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.CompletedAt = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetCompletedAt() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.CompletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m migrationProgressMods) RandomCompletedAt(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m migrationProgressMods) RandomCompletedAtNotNull(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) ErrorMessage(val sql.Null[string]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.ErrorMessage = func() sql.Null[string] { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) ErrorMessageFunc(f func() sql.Null[string]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.ErrorMessage = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetErrorMessage() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.ErrorMessage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m migrationProgressMods) RandomErrorMessage(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.ErrorMessage = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m migrationProgressMods) RandomErrorMessageNotNull(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.ErrorMessage = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) RetryCount(val sql.Null[int32]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.RetryCount = func() sql.Null[int32] { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) RetryCountFunc(f func() sql.Null[int32]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.RetryCount = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetRetryCount() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.RetryCount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m migrationProgressMods) RandomRetryCount(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.RetryCount = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m migrationProgressMods) RandomRetryCountNotNull(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.RetryCount = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m migrationProgressMods) MaxRetries(val sql.Null[int32]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MaxRetries = func() sql.Null[int32] { return val }
	})
}

// Set the Column from the function
func (m migrationProgressMods) MaxRetriesFunc(f func() sql.Null[int32]) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MaxRetries = f
	})
}

// Clear any values for the column
func (m migrationProgressMods) UnsetMaxRetries() MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MaxRetries = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m migrationProgressMods) RandomMaxRetries(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MaxRetries = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m migrationProgressMods) RandomMaxRetriesNotNull(f *faker.Faker) MigrationProgressMod {
	return MigrationProgressModFunc(func(_ context.Context, o *MigrationProgressTemplate) {
		o.MaxRetries = func() sql.Null[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return sql.Null[int32]{V: val, Valid: true}
		}
	})
}

func (m migrationProgressMods) WithParentsCascading() MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		if isDone, _ := migrationProgressWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = migrationProgressWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewIdentityMapping(ctx, IdentityMappingMods.WithParentsCascading())
			m.WithMappingIdentityMapping(related).Apply(ctx, o)
		}
		{

			related := o.f.NewKeyRotationMigration(ctx, KeyRotationMigrationMods.WithParentsCascading())
			m.WithMigrationKeyRotationMigration(related).Apply(ctx, o)
		}
	})
}

func (m migrationProgressMods) WithMappingIdentityMapping(rel *IdentityMappingTemplate) MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		o.r.MappingIdentityMapping = &migrationProgressRMappingIdentityMappingR{
			o: rel,
		}
	})
}

func (m migrationProgressMods) WithNewMappingIdentityMapping(mods ...IdentityMappingMod) MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		related := o.f.NewIdentityMapping(ctx, mods...)

		m.WithMappingIdentityMapping(related).Apply(ctx, o)
	})
}

func (m migrationProgressMods) WithoutMappingIdentityMapping() MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		o.r.MappingIdentityMapping = nil
	})
}

func (m migrationProgressMods) WithMigrationKeyRotationMigration(rel *KeyRotationMigrationTemplate) MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		o.r.MigrationKeyRotationMigration = &migrationProgressRMigrationKeyRotationMigrationR{
			o: rel,
		}
	})
}

func (m migrationProgressMods) WithNewMigrationKeyRotationMigration(mods ...KeyRotationMigrationMod) MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		related := o.f.NewKeyRotationMigration(ctx, mods...)

		m.WithMigrationKeyRotationMigration(related).Apply(ctx, o)
	})
}

func (m migrationProgressMods) WithoutMigrationKeyRotationMigration() MigrationProgressMod {
	return MigrationProgressModFunc(func(ctx context.Context, o *MigrationProgressTemplate) {
		o.r.MigrationKeyRotationMigration = nil
	})
}
