// Code generated by MockGen. DO NOT EDIT.
// Source: internal/testutil/mocks/nats_interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nats_go "github.com/nats-io/nats.go"
)

// MockNatsConn is a mock of NatsConn interface.
type MockNatsConn struct {
	ctrl     *gomock.Controller
	recorder *MockNatsConnMockRecorder
}

// MockNatsConnMockRecorder is the mock recorder for MockNatsConn.
type MockNatsConnMockRecorder struct {
	mock *MockNatsConn
}

// NewMockNatsConn creates a new mock instance.
func NewMockNatsConn(ctrl *gomock.Controller) *MockNatsConn {
	mock := &MockNatsConn{ctrl: ctrl}
	mock.recorder = &MockNatsConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsConn) EXPECT() *MockNatsConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNatsConn) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockNatsConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNatsConn)(nil).Close))
}

// Drain mocks base method.
func (m *MockNatsConn) Drain() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain")
	ret0, _ := ret[0].(error)
	return ret0
}

// Drain indicates an expected call of Drain.
func (mr *MockNatsConnMockRecorder) Drain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockNatsConn)(nil).Drain))
}

// JetStream mocks base method.
func (m *MockNatsConn) JetStream(opts ...nats_go.JSOpt) (JetStreamContext, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "JetStream", varargs...)
	ret0, _ := ret[0].(JetStreamContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JetStream indicates an expected call of JetStream.
func (mr *MockNatsConnMockRecorder) JetStream(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JetStream", reflect.TypeOf((*MockNatsConn)(nil).JetStream), opts...)
}

// MockJetStreamContext is a mock of JetStreamContext interface.
type MockJetStreamContext struct {
	ctrl     *gomock.Controller
	recorder *MockJetStreamContextMockRecorder
}

// MockJetStreamContextMockRecorder is the mock recorder for MockJetStreamContext.
type MockJetStreamContextMockRecorder struct {
	mock *MockJetStreamContext
}

// NewMockJetStreamContext creates a new mock instance.
func NewMockJetStreamContext(ctrl *gomock.Controller) *MockJetStreamContext {
	mock := &MockJetStreamContext{ctrl: ctrl}
	mock.recorder = &MockJetStreamContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetStreamContext) EXPECT() *MockJetStreamContextMockRecorder {
	return m.recorder
}

// AddStream mocks base method.
func (m *MockJetStreamContext) AddStream(cfg *nats_go.StreamConfig, opts ...nats_go.JSOpt) (*nats_go.StreamInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{cfg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddStream", varargs...)
	ret0, _ := ret[0].(*nats_go.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStream indicates an expected call of AddStream.
func (mr *MockJetStreamContextMockRecorder) AddStream(cfg interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cfg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStream", reflect.TypeOf((*MockJetStreamContext)(nil).AddStream), varargs...)
}

// DeleteStream mocks base method.
func (m *MockJetStreamContext) DeleteStream(name string, opts ...nats_go.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStream", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockJetStreamContextMockRecorder) DeleteStream(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockJetStreamContext)(nil).DeleteStream), varargs...)
}

// Publish mocks base method.
func (m *MockJetStreamContext) Publish(subj string, data []byte, opts ...nats_go.PubOpt) (*nats_go.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*nats_go.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockJetStreamContextMockRecorder) Publish(subj, data interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockJetStreamContext)(nil).Publish), varargs...)
}

// StreamInfo mocks base method.
func (m *MockJetStreamContext) StreamInfo(stream string, opts ...nats_go.JSOpt) (*nats_go.StreamInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamInfo", varargs...)
	ret0, _ := ret[0].(*nats_go.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamInfo indicates an expected call of StreamInfo.
func (mr *MockJetStreamContextMockRecorder) StreamInfo(stream interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamInfo", reflect.TypeOf((*MockJetStreamContext)(nil).StreamInfo), varargs...)
}
