name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
      - name: Run unit tests
        run: make test-unit

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p bin
          go build -o bin/hashpost-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd/server
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hashpost-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/hashpost-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hashpost
          POSTGRES_PASSWORD: hashpost_test
          POSTGRES_DB: hashpost_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U hashpost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5433 -U hashpost && break
            sleep 2
          done
      - name: Setup test database
        env:
          DATABASE_URL: postgres://hashpost:hashpost_test@localhost:5433/postgres?sslmode=disable
        run: |
          psql -c "DROP DATABASE IF EXISTS hashpost_test;" || true
          psql -c "CREATE DATABASE hashpost_test;" || true
      - name: Run database migrations
        env:
          DATABASE_URL: postgres://hashpost:hashpost_test@localhost:5433/hashpost_test?sslmode=disable
        run: ./scripts/migrate.sh up
      - name: Run integration tests
        env:
          DATABASE_URL: postgres://hashpost:hashpost_test@localhost:5433/hashpost_test?sslmode=disable
          LOG_LEVEL: error
        run: go test -v -tags=integration ./internal/api/integration/... ./internal/database/dao/integration/... 