-- Drop AppView performance indexes
DROP INDEX IF EXISTS idx_appview_subforums_post_count;
DROP INDEX IF EXISTS idx_appview_subforums_subscriber_count;
DROP INDEX IF EXISTS idx_appview_users_post_count;
DROP INDEX IF EXISTS idx_appview_users_reputation;
DROP INDEX IF EXISTS idx_appview_comments_content_search;
DROP INDEX IF EXISTS idx_appview_posts_content_search;
DROP INDEX IF EXISTS idx_appview_subscriptions_subforum_created;
DROP INDEX IF EXISTS idx_appview_subscriptions_user_created;
DROP INDEX IF EXISTS idx_appview_votes_comment_vote_type;
DROP INDEX IF EXISTS idx_appview_votes_post_vote_type;
DROP INDEX IF EXISTS idx_appview_comments_atproto_uri;
DROP INDEX IF EXISTS idx_appview_posts_atproto_uri;
DROP INDEX IF EXISTS idx_appview_comments_author_created;
DROP INDEX IF EXISTS idx_appview_comments_post_created;
DROP INDEX IF EXISTS idx_appview_posts_subforum_score;
DROP INDEX IF EXISTS idx_appview_posts_subforum_author_created;
DROP INDEX IF EXISTS idx_appview_posts_author_created;
